language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: "<REPO TOKEN GOES HERE>"
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: o2UehV12RFHrMmwfR+Q/A8gyBVRNmMDgOlJhlxGGg0yOGZ1RfzwJih1jdmxDL5JYp1BqKk/pw4OdL8vnAql88fP9RaZlZs0grIh7vwU/tVmYS2r5zAvgJxENk8AqjlFZZX8neKKyCMu8KPddB/D2OUybDuiPofMcnv5/jK9QSKNhDME2IlNXOpWnqj+hJYTok69m2hwYu0hfwu09qr9QTG4A5kkIXVn7sCDkR0lnnc6ctgeiSPKM2GTWq70DiMAYWhp6LtYOBZTElluVjG4PSMwX0YardWuMIRtUSrekGngPUqNb6a188BPfrUlBOTuRhbX6KFKytou0cWEGlgrd9CO/3S/gIB04unw6BHkYZttLTVhTTnTTDusoTdzGdEF16ttMKNKrVBQZj/n8Nw1W9JqcMV2wXCvuWRyB4gZWAURNoP9KrQi9+w0MFLboN+ZWTVbIhOPN6PheAo1piyUHKNmPZR22fOEmN27dKgJMNr92luu+FztgmyZVeME/AotcwLp2KKbsX4V8dPLDa05D6HFZbilBG0MMdzgc0ZC19G1AaULjEpfYPXU9UzXxHCYYdV1ot63HLBz2QwTjeI9lg95nC3cYVDHD80KxKqqw3wjdE8uG2IQpSLv9n1y34Q4LeByoca9A9y7iQ4e7rgadianoF7f7GPUYIBGj6kO4MXA=
  on:
    tags: true
    branches: true
after_success:
- bash <(curl -s https://codecov.io/bash)
